import streamlit as st

def mostrar_manual():
    st.markdown("""""")
    st.markdown("""## 📘 Manual - Cómo usar esta herramienta""")
    st.markdown("""""")
    st.markdown("""### 📊 ¿Qué hace esta herramienta?""")
    st.markdown("""Esta calculadora de cuartiles utiliza el método `PERCENTIL.EXC` (como en Excel) para dividir métricas numéricas en 4 grupos iguales. Permite:""")
    st.markdown("""- Calcular cuartiles de forma automática sobre distintos indicadores.""")
    st.markdown("""- Seleccionar **dos conjuntos de métricas que se cuartilizan de manera distinta** ).""")
    st.markdown("""- Aplicar **cuartilizado inverso** para métricas como NPS, SAT o Ventas.""")
    st.markdown("""- Agregar columnas con **intervalos numéricos** para interpretar mejor los valores.""")
    st.markdown("""""")
    st.markdown("""---""")
    st.markdown("""""")
    st.markdown("""### 🧑‍💻 ¿Cómo se utiliza?""")
    st.markdown("""""")
    st.markdown("""1. **Cargar el archivo Excel** exportado desde Power BI usando el botón **"📂 Browse files"**.""")
    st.markdown("""2. **Seleccionar uno o más identificadores**, como:""")
    st.markdown("""   - Asesor""")
    st.markdown("""   - Líder""")
    st.markdown("""   - Llamadas""")
    st.markdown("""   Esto permitirá mantener la relación con la persona o entidad analizada.""")
    st.markdown("""3. **Seleccionar el primer grupo de métricas** (por ejemplo: TMO, TOL).""")
    st.markdown("""4. **Seleccionar el segundo grupo de métricas** (opcional). Marcar el checkbox si esas métricas deben tener cuartiles invertidos (ej: NPS, SAT, Ventas).""")
    st.markdown("""5. Presionar el botón **"📈 Calcular cuartiles"**.""")
    st.markdown("""6. Descargar el resultado con **"📥 Descargar Excel calculado"**.""")
    st.markdown("""""")
    st.markdown("""---""")
    st.markdown("""""")
    st.markdown("""### 📈 ¿Qué hace el botón 'Calcular cuartiles'?""")
    st.markdown("""- Procesa cada grupo de métricas y genera:""")
    st.markdown("""  - Columna `🔢 _Cuartil`: indica Q1, Q2, Q3 o Q4.""")
    st.markdown("""  - Columna `📏 _Intervalo` (opcional): muestra el rango exacto al que pertenece cada valor.""")
    st.markdown("""""")
    st.markdown("""---""")
    st.markdown("""""")
    st.markdown("""### 📐 ¿Cómo se calculan los cuartiles?""")
    st.markdown("""- Se usa el método `PERCENTIL.EXC` (como en Excel).""")
    st.markdown("""- El cálculo divide los datos en cuartiles Q1 a Q4 excluyendo los extremos 0% y 100%.""")
    st.markdown("""- Si se activa el modo **invertido**, los valores altos quedan en Q1 y los bajos en Q4.""")
    st.markdown("""""")
    st.markdown("""---""")
    st.markdown("""""")
    st.markdown("""### 🔍 ¿Qué significan los intervalos?""")
    st.markdown("""Los cuartiles se definen como:""")
    st.markdown("""""")
    st.markdown("""- **Q1 →** `[mín, P25)` → 25% más bajo""")
    st.markdown("""- **Q2 →** `[P25, P50)`""")
    st.markdown("""- **Q3 →** `[P50, P75)`""")
    st.markdown("""- **Q4 →** `[P75, máx]` → 25% más alto""")
    st.markdown("""""")
    st.markdown("""Si se invierte el sentido, se intercambian los significados de Q1 y Q4.""")
    st.markdown("""""")
    st.markdown("""---""")
    st.markdown("""""")
    st.markdown("""### 📄 ¿Qué incluye el Excel exportado?""")
    st.markdown("""""")
    st.markdown("""1. **Hoja "Resultados"**:""")
    st.markdown("""   - Valores originales""")
    st.markdown("""   - Cuartiles calculados""")
    st.markdown("""   - Intervalos (si fueron activados)""")
    st.markdown("""""")
    st.markdown("""2. **Hoja "Intervalos"**:""")
    st.markdown("""   - Muestra los valores de P25, P50 y P75 para cada métrica""")
    st.markdown("""   - Ayuda a entender cómo se construyó cada cuartil""")
    st.markdown("""""")
    st.markdown("""---""")
    st.markdown("""""")
    st.markdown("""### 🧠 Ejemplo de configuración""")
    st.markdown("""""")
    st.markdown("""- **Grupo 1**: TMO, TOL (sin invertir)""")
    st.markdown("""- **Grupo 2**: NPS, SAT (invertido ✅)""")
    st.markdown("""""")
    st.markdown("""Esto te permite:""")
    st.markdown("""- Comparar rendimiento en base a cuartiles""")
    st.markdown("""- Entender rangos de desempeño""")
    st.markdown("""- Aplicar filtros y generar reportes claros""")
    st.markdown("""""")
    st.markdown("""💡 Recordá que las filas que comienzan con **"Total"** se ignoran automáticamente en los cálculos.""")
    st.markdown("""""")
